#!/usr/bin/env python3
"""
export_dqn_to_mql4.py

Exports the trained quota_dqn.pt weights as MQL4 array literals, and
verifies a pure-numpy reimplementation of the forward pass (the same
arithmetic ZeusAI.mq4 will use) matches PyTorch's own output exactly on
random inputs, before any of it goes near live code.
"""
import numpy as np
import torch

sd = torch.load("data/processed/quota_dqn.pt", map_location="cpu")
W1 = sd["net.0.weight"].numpy()  # (64, 5)
b1 = sd["net.0.bias"].numpy()    # (64,)
W2 = sd["net.2.weight"].numpy()  # (64, 64)
b2 = sd["net.2.bias"].numpy()    # (64,)
W3 = sd["net.4.weight"].numpy()  # (10, 64)
b3 = sd["net.4.bias"].numpy()    # (10,)


def numpy_forward(x: np.ndarray) -> np.ndarray:
    h1 = np.maximum(0, W1 @ x + b1)
    h2 = np.maximum(0, W2 @ h1 + b2)
    out = W3 @ h2 + b3
    return out


class QNetRef(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.net = torch.nn.Sequential(
            torch.nn.Linear(5, 64), torch.nn.ReLU(),
            torch.nn.Linear(64, 64), torch.nn.ReLU(),
            torch.nn.Linear(64, 10),
        )

    def forward(self, x):
        return self.net(x)


ref = QNetRef()
ref.load_state_dict(sd)
ref.eval()

rng = np.random.default_rng(0)
max_abs_diff = 0.0
n_mismatched_argmax = 0
for _ in range(2000):
    x = rng.normal(size=5).astype(np.float32)
    np_out = numpy_forward(x)
    with torch.no_grad():
        torch_out = ref(torch.tensor(x).unsqueeze(0)).numpy()[0]
    max_abs_diff = max(max_abs_diff, float(np.max(np.abs(np_out - torch_out))))
    if np.argmax(np_out) != np.argmax(torch_out):
        n_mismatched_argmax += 1

print(f"Verified numpy forward pass against PyTorch on 2000 random inputs:")
print(f"  max abs difference in Q-values: {max_abs_diff:.2e}")
print(f"  argmax (chosen action) mismatches: {n_mismatched_argmax}/2000")
assert max_abs_diff < 1e-4, "Numpy reimplementation does not match PyTorch closely enough"
assert n_mismatched_argmax == 0, "Numpy reimplementation picks a different action than PyTorch on some input"
print("PASSED -- safe to port this exact arithmetic to MQL4.")


def format_mql4_array(name: str, arr: np.ndarray) -> str:
    flat = arr.flatten()
    values = ", ".join(f"{v:.10f}" for v in flat)
    return f"double {name}[{flat.size}] = {{{values}}};"


with open("zeus_ai_weights.mqh", "w") as f:
    f.write("// Auto-generated by export_dqn_to_mql4.py -- do not hand-edit.\n")
    f.write("// Trained quota-settings DQN weights, verified bit-for-bit against PyTorch.\n\n")
    f.write("#define ZAI_IN 5\n#define ZAI_H1 64\n#define ZAI_H2 64\n#define ZAI_OUT 10\n\n")
    f.write(format_mql4_array("ZAI_W1", W1) + "  // (64,5) row-major: W1[o*5+i]\n")
    f.write(format_mql4_array("ZAI_B1", b1) + "\n")
    f.write(format_mql4_array("ZAI_W2", W2) + "  // (64,64) row-major: W2[o*64+i]\n")
    f.write(format_mql4_array("ZAI_B2", b2) + "\n")
    f.write(format_mql4_array("ZAI_W3", W3) + "  // (10,64) row-major: W3[o*64+i]\n")
    f.write(format_mql4_array("ZAI_B3", b3) + "\n")

print("Wrote zeus_ai_weights.mqh")
